from datetime import datetime
from typing import Any

from .job import Job

class BaseRegistry:
    count: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_job_ids(self, start: int = ..., end: int = ...) -> list[str]: ...
    def get_expiration_time(self, job: Job) -> datetime: ...

class ScheduledJobRegistry(BaseRegistry):
    def get_scheduled_time(self, job_or_id: Job | str) -> datetime: ...
