name: publish
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pdm
          key: ${{ runner.os }}-pdm-${{ hashFiles('**/pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pdm-
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm run -r build
      - run: PYPI_API_TOKEN=${{ secrets.PYPI_API_TOKEN }} pnpm run -r publish
      - run: cd runtime && pdm run python -m twine upload --repository-url ${{ secrets.NEXUS_URL }} dist/* --username ${{ secrets.NEXUS_USERNAME }} --password ${{ secrets.NEXUS_PASSWORD }}
